language: ruby
cache: bundler
bundler_args: --without console
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ -d coverage ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
  - bundle exec rake spec
  - RAILS_ENV=production bundle exec rspec --tag production_env
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - 2.3.8
  - truffleruby
matrix:
  allow_failures:
    - rvm: truffleruby
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
