name: dry-rails
codacy_id: d4677ea0c4c2497bb1af1b3ac31552f4
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica@gmail.com"]
  summary: "The official dry-rb railtie for Ruby on Rails"
  description: "The railtie provides a smooth integration with dry-system, integrates dry-rb components with the controllers and more"
  files: []
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [dry-system, "~> 0.14"]
    - [dry-validation, "~> 1.4"]
    - [dry-types, "~> 1.2"]
    - [dry-monads, "~> 1.3"]
    - [dry-matcher, "~> 0.8"]
